### PR TITLE
Add help mojo

### LINKED ISSUE #46: Work on "help" goal:   `mvn boost:help`
Maybe this should be tracked under an epic not just an issue, but throwing this out there for now:

### PR DESCRIPTION
**Pull request by awisniew90**
Fixes #46

### CODE REVIEW

**Comment by awisniew90** [comment]
boost_help_debug
boost_help_docker-build
boost_help_docker-push
boost_help_package
boost_help_run
boost_help_start
boost_help_stop
boost_help

**Comment by awisniew90** [comment]
Main help goal:

boost_help

**Comment by awisniew90** [comment]
Details from each goal:

boost_help_debug

boost_help_docker-build

boost_help_docker-push

boost_help_package

boost_help_run

boost_help_start

boost_help_stop

**Comment by awisniew90** [comment]
@cherylking  -  I attached screen shots above. The content is taken directly from the comments of the Mojo classes and parameter annotations. We can change any of that if things don't look right.

**Comment by cherylking** [comment]
@awisniew90 Thanks Adam! Looks good. I'm going to merge it.

**Pull request merged**
